[package]
name = "net-commander"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
crossterm = "*"
clap = { version = "*", features = ["derive"] }
tui = "*"
anyhow = "*"