[package]
name = "hello-world-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"
figlet-rs = "*"
anyhow = "*"
crossterm = "*"
tokio = { version = "*", features = ["full"] }
clap = { version = "*", features = ["derive"] }
tui = "*"