[package]
name = "secure-notes"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "*", features = ["full"] }
crossterm = "*"
anyhow = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
ring = "*"
base64 = "*"
zeroize = "*"
rand = "*"